# This is a basic workflow to help you get started with Actions

name: pull_image_jfrog_ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      APPVERSION: "7.59.9"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          docker pull releases-docker.jfrog.io/ubi9/ubi-minimal:9.1.0.1793
          docker tag releases-docker.jfrog.io/ubi9/ubi-minimal:9.1.0.1793 ailuoli/ubi-minimal:9.1.0.1793

          docker pull releases-docker.jfrog.io/ubi9/ubi-minimal:8.6-902
          docker tag releases-docker.jfrog.io/ubi9/ubi-minimal:8.6-902 ailuoli/ubi-minimal:8.6-902

          docker pull releases-docker.jfrog.io/jfrog/xray-analysis:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/xray-analysis:${APPVERSION} ailuoli/xray-analysis:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/xray-indexer:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/xray-indexer:${APPVERSION} ailuoli/xray-indexer:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/xray-persist:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/xray-persist:${APPVERSION} ailuoli/xray-persist:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/xray-server:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/xray-server:${APPVERSION} ailuoli/xray-server:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/router:7.67.0
          docker tag releases-docker.jfrog.io/jfrog/router:7.67.0 ailuoli/router:7.67.0
          
          docker pull releases-docker.jfrog.io/jfrog/router:7.45.0
          docker tag releases-docker.jfrog.io/jfrog/router:7.45.0 ailuoli/router:7.45.0
          
          docker pull releases-docker.jfrog.io/jfrog/observability:1.13.1
          docker tag releases-docker.jfrog.io/jfrog/observability:1.13.1 ailuoli/observability:1.13.1   
          
          docker pull releases-docker.jfrog.io/jfrog/observability:1.9.3
          docker tag releases-docker.jfrog.io/jfrog/observability:1.9.3 ailuoli/observability:1.9.3
          
          docker pull releases-docker.jfrog.io/jfrog/artifactory-pro:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/artifactory-pro:${APPVERSION} ailuoli/artifactory-pro:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/nginx-artifactory-pro:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/nginx-artifactory-pro:${APPVERSION} ailuoli/nginx-artifactory-pro:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/distribution-distribution:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/distribution-distribution:${APPVERSION} ailuoli/distribution-distribution:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/elasticsearch-sg:7.17.6
          docker tag releases-docker.jfrog.io/jfrog/elasticsearch-sg:7.17.6 ailuoli/elasticsearch-sg:7.17.6
          
          docker pull releases-docker.jfrog.io/jfrog/insight-server:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/insight-server:${APPVERSION} ailuoli/insight-server:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/insight-scheduler:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/insight-scheduler:${APPVERSION} ailuoli/insight-scheduler:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/jfrog/pdn/server:${APPVERSION}
          docker tag releases-docker.jfrog.io/jfrog/pdn/server:${APPVERSION} ailuoli/pdn-server:${APPVERSION}
          
          docker pull releases-docker.jfrog.io/alpine:3.14.2
          docker tag releases-docker.jfrog.io/alpine:3.14.2 ailuoli/alpine:3.14.2

      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push ailuoli/ubi-minimal:9.1.0.1793
          docker push ailuoli/ubi-minimal:8.6-902
          docker push ailuoli/xray-analysis:${APPVERSION}
          docker push ailuoli/xray-indexer:${APPVERSION}
          docker push ailuoli/xray-persist:${APPVERSION}
          docker push ailuoli/xray-server:${APPVERSION}
          docker push ailuoli/router:7.67.0
          docker push ailuoli/router:7.45.0 
          docker push ailuoli/observability:1.13.1
          docker push ailuoli/observability:1.9.3 
          docker push ailuoli/artifactory-pro:${APPVERSION}
          docker push ailuoli/nginx-artifactory-pro:${APPVERSION}
          docker push ailuoli/distribution-distribution:${APPVERSION}
          docker push ailuoli/elasticsearch-sg:7.17.6
          docker push ailuoli/insight-server:${APPVERSION}
          docker push ailuoli/insight-scheduler:${APPVERSION}
          docker push ailuoli/pdn-server:${APPVERSION}
          docker push ailuoli/alpine:3.14.2
