# This is a basic workflow to help you get started with Actions

name: pull_image_jfrog_ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull releases-docker.jfrog.io/ubi9/ubi-minimal:9.1.0.1793
          docker tag releases-docker.jfrog.io/ubi9/ubi-minimal:9.1.0.1793 ailuoli/ubi-minimal:9.1.0.1793
          
          docker pull releases-docker.jfrog.io/jfrog/xray-analysis:latest
          docker tag releases-docker.jfrog.io/jfrog/xray-analysis:latest ailuoli/xray-analysis:latest
          
          docker pull releases-docker.jfrog.io/jfrog/xray-indexer:latest
          docker tag releases-docker.jfrog.io/jfrog/xray-indexer:latest ailuoli/xray-indexer:latest
          
          docker pull releases-docker.jfrog.io/jfrog/xray-persist:latest
          docker tag releases-docker.jfrog.io/jfrog/xray-persist:latest ailuoli/xray-persist:latest
          
          docker pull releases-docker.jfrog.io/jfrog/xray-server:latest
          docker tag releases-docker.jfrog.io/jfrog/xray-server:latest ailuoli/xray-server:latest
          
          docker pull releases-docker.jfrog.io/jfrog/router:7.67.0
          docker tag releases-docker.jfrog.io/jfrog/router:7.67.0 ailuoli/router:7.67.0
          
          docker pull releases-docker.jfrog.io/jfrog/observability:1.13.1
          docker tag releases-docker.jfrog.io/jfrog/observability:1.13.1 ailuoli/observability:1.13.1      
      

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push ailuoli/ubi-minimal:9.1.0.1793
          docker push ailuoli/xray-analysis:latest
          docker push ailuoli/xray-indexer:latest
          docker push ailuoli/xray-persist:latest
          docker push ailuoli/xray-server:latest
          docker push ailuoli/router:7.67.0
          docker push ailuoli/observability:1.13.1      

          
