# This is a basic workflow to help you get started with Actions

name: pull_image_prometheus-stack_ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      HOME_CHART_APPVERSION: "v0.70.0"
      KUBE_WEBHOOK_CERTGEN_VERSION: "v20221220-controller-v1.5.1-58-g787ea74b6"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:${KUBE_WEBHOOK_CERTGEN_VERSION}
          docker tag registry.k8s.io/ingress-nginx/kube-webhook-certgen:${KUBE_WEBHOOK_CERTGEN_VERSION} ailuoli/kube-webhook-certgen:${KUBE_WEBHOOK_CERTGEN_VERSION}
          
          docker pull quay.io/prometheus-operator/prometheus-config-reloader:${HOME_CHART_APPVERSION}
          docker tag quay.io/prometheus-operator/prometheus-config-reloader:${HOME_CHART_APPVERSION} ailuoli/prometheus-config-reloader:${HOME_CHART_APPVERSION}


      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push ailuoli/kube-webhook-certgen:${KUBE_WEBHOOK_CERTGEN_VERSION}
          docker push ailuoli/prometheus-config-reloader:${HOME_CHART_APPVERSION}

          
          
