# This is a basic workflow to help you get started with Actions

name: pull_image_tekton_ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PIPELINE_VERSION: "v0.47.0"
      TRIGGER_VERSION: "v0.23.1"
      DASHBOARD_VERSION: "v0.35.0"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:${PIPELINE_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:${PIPELINE_VERSION} ailuoli/tektoncd-pipeline-cmd-controller:${PIPELINE_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:${PIPELINE_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:${PIPELINE_VERSION}ailuoli/tektoncd-pipeline-cmd-entrypoint:${PIPELINE_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:${PIPELINE_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:${PIPELINE_VERSION} ailuoli/tektoncd-pipeline-cmd-nop:${PIPELINE_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:${PIPELINE_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:${PIPELINE_VERSION} ailuoli/tektoncd-pipeline-cmd-sidecarlogresults:${PIPELINE_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:${PIPELINE_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:${PIPELINE_VERSION} ailuoli/tektoncd-pipeline-cmd-workingdirinit:${PIPELINE_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:${PIPELINE_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:${PIPELINE_VERSION} ailuoli/tektoncd-pipeline-cmd-resolvers:${PIPELINE_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:${PIPELINE_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:${PIPELINE_VERSION} ailuoli/tektoncd-pipeline-cmd-webhook:${PIPELINE_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:${DASHBOARD_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:${DASHBOARD_VERSION} ailuoli/tektoncd-dashboard-cmd-dashboard:${DASHBOARD_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:${TRIGGER_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:${TRIGGER_VERSION} ailuoli/tektoncd-triggers-cmd-controller:${TRIGGER_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:${TRIGGER_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:${TRIGGER_VERSION} ailuoli/tektoncd-triggers-cmd-eventlistenersink:${TRIGGER_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:${TRIGGER_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:${TRIGGER_VERSION} ailuoli/tektoncd-triggers-cmd-webhook:${TRIGGER_VERSION}
          
          docker pull gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:${TRIGGER_VERSION}
          docker tag gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:${TRIGGER_VERSION} ailuoli/tektoncd-triggers-cmd-interceptors:${TRIGGER_VERSION}
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Runs a set of commands using the runners shell
      - name: Push to Docker Registry
        run: |
          docker push ailuoli/tektoncd-pipeline-cmd-controller:${PIPELINE_VERSION}
          docker push ailuoli/tektoncd-pipeline-cmd-entrypoint:${PIPELINE_VERSION}
          docker push ailuoli/tektoncd-pipeline-cmd-nop:${PIPELINE_VERSION}
          docker push ailuoli/tektoncd-pipeline-cmd-sidecarlogresults:${PIPELINE_VERSION}
          docker push ailuoli/tektoncd-pipeline-cmd-workingdirinit:${PIPELINE_VERSION}
          docker push ailuoli/tektoncd-pipeline-cmd-resolvers:${PIPELINE_VERSION}
          docker push ailuoli/tektoncd-pipeline-cmd-webhook:${PIPELINE_VERSION}
          docker push ailuoli/tektoncd-dashboard-cmd-dashboard:${DASHBOARD_VERSION}
          docker push ailuoli/tektoncd-triggers-cmd-controller:${TRIGGER_VERSION}
          docker push ailuoli/tektoncd-triggers-cmd-eventlistenersink:${TRIGGER_VERSION}
          docker push ailuoli/tektoncd-triggers-cmd-webhook:${TRIGGER_VERSION}
          docker push ailuoli/tektoncd-triggers-cmd-interceptors:${TRIGGER_VERSION}
          
          

